export const states = [
    { "key": "andhra_pradesh", "name": "Andhra Pradesh" },
    { "key": "arunachal_pradesh", "name": "Arunachal Pradesh" },
    { "key": "assam", "name": "Assam" },
    { "key": "bihar", "name": "Bihar" },
    { "key": "chhattisgarh", "name": "Chhattisgarh" },
    { "key": "goa", "name": "Goa" },
    { "key": "gujarat", "name": "Gujarat" },
    { "key": "haryana", "name": "Haryana" },
    { "key": "himachal_pradesh", "name": "Himachal Pradesh" },
    { "key": "jharkhand", "name": "Jharkhand" },
    { "key": "karnataka", "name": "Karnataka" },
    { "key": "kerala", "name": "Kerala" },
    { "key": "madhya_pradesh", "name": "Madhya Pradesh" },
    { "key": "maharashtra", "name": "Maharashtra" },
    { "key": "manipur", "name": "Manipur" },
    { "key": "meghalaya", "name": "Meghalaya" },
    { "key": "mizoram", "name": "Mizoram" },
    { "key": "nagaland", "name": "Nagaland" },
    { "key": "odisha", "name": "Odisha" },
    { "key": "punjab", "name": "Punjab" },
    { "key": "rajasthan", "name": "Rajasthan" },
    { "key": "sikkim", "name": "Sikkim" },
    { "key": "tamil_nadu", "name": "Tamil Nadu" },
    { "key": "telangana", "name": "Telangana" },
    { "key": "tripura", "name": "Tripura" },
    { "key": "uttar_pradesh", "name": "Uttar Pradesh" },
    { "key": "uttarakhand", "name": "Uttarakhand" },
    { "key": "west_bengal", "name": "West Bengal" }
  ]
  